In [1]:
import numpy as np
import itertools
# all possible int vectors of size 2, values between 0 and 5
a = np.arange(0, 5)
b = np.arange(0, 5)

all_possible_vectors = itertools.product(a, b)
sauce = np.array(list(all_possible_vectors)[0])

sauce



array([0, 0])

In [13]:
scale_list = itertools.product(np.arange(6) + 0.5, repeat=2)
scale_list = np.array(list(scale_list))
scale_list = scale_list * 0.1

In [1]:
NUM_OF_PARAMS = 2

In [14]:
np.random.randint(0, 5, NUM_OF_PARAMS)*0.1

array([0. , 0.3])

In [15]:
scale_list = itertools.product(np.arange(6) + 0.5, repeat=2)
scale_list = np.array(list(scale_list))
scale_list * 0.1

array([[0.05, 0.05],
       [0.05, 0.15],
       [0.05, 0.25],
       [0.05, 0.35],
       [0.05, 0.45],
       [0.05, 0.55],
       [0.15, 0.05],
       [0.15, 0.15],
       [0.15, 0.25],
       [0.15, 0.35],
       [0.15, 0.45],
       [0.15, 0.55],
       [0.25, 0.05],
       [0.25, 0.15],
       [0.25, 0.25],
       [0.25, 0.35],
       [0.25, 0.45],
       [0.25, 0.55],
       [0.35, 0.05],
       [0.35, 0.15],
       [0.35, 0.25],
       [0.35, 0.35],
       [0.35, 0.45],
       [0.35, 0.55],
       [0.45, 0.05],
       [0.45, 0.15],
       [0.45, 0.25],
       [0.45, 0.35],
       [0.45, 0.45],
       [0.45, 0.55],
       [0.55, 0.05],
       [0.55, 0.15],
       [0.55, 0.25],
       [0.55, 0.35],
       [0.55, 0.45],
       [0.55, 0.55]])

In [9]:
np.linspace(0.1, 1, 4) + 0.15

array([0.25, 0.55, 0.85, 1.15])

In [1]:
import gym
gym.make("StrikerOracle-v0")

UnregisteredEnv: No registered env with id: StrikerOracle-v0